name: Terraform
on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "terraform/**"
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_and_test:
    name: Build Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run Terraform Plan
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: plan-run
        with:
          workspace: "az-hub-spoke-private-endpoint/terraform"
        #   configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
          plan_only: true