name: Terraform
on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "terraform/**"
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_and_test:
    name: Build Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "terraform/"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Terraform Validate
        uses: hashicorp/setup-terraform@v2
        id: validate
        run: terraform validate -no-color
        
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true